### ISSUE TITLE
Microsoft Edge Selenium Error exit value - 1073741512

### ISSUE THREAD

**Issue by SudeeptMohan** [xianyi/OpenBLAS#1367]
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: -1073741512 (Exit value: -1073741512)
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:150)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:139)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:96)
	at packageFF.browserAutomation.main(browserAutomation.java:40)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:14371/status] to be available after 20002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
	... 9 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 10 more

**Comment by martin-frbg** [comment]
Could you please provide some more context for this error message ? From what you wrote, it is unclear why you think the OpenBLAS math library could be involved in any way - all I see is that the selenium software failed to connect to some unspecified webservice it expected to find on port 14371 of your pc.

**Comment by SudeeptMohan** [comment]
In the code i am first setting the property via command -
		System.setProperty("webdriver.edge.driver","C:\\\\Marionette\\MicrosoftWebDriver.exe"); 
Then comes the command -
WebDriver driver5 = new EdgeDriver(); 
Which i feel might be failed due to mysterious reasons, i am not sure?

**Comment by martin-frbg** [comment]
Sorry, I still do not see what this has to do with the OpenBLAS project. Is your code using any linear algebra functions from BLAS or LAPACK at all ?

**Comment by SudeeptMohan** [comment]
This is not connected with OpenBLAS project, this query is for Selenium-MicrosoftWebdriver.My code is not using any linear algebra functions from BLAS or LAPACK at all.

**Comment by martin-frbg** [comment]
Please repost your question at https://github.com/SeleniumHQ/selenium/issues (I guess) then, I have no idea why it ended up here.

**Comment by SudeeptMohan** [comment]
Now,This issue is reported at - https://github.com/SeleniumHQ/selenium/issues/5123
I guess it will be okay to close it over here under OpenBLAS
