### ISSUE TITLE
not able to make python bindings 

### ISSUE THREAD

**Issue by vigneshmj1997** [xianyi/OpenBLAS#2701]
i wanna make python bindings without using a docker 

ERROR: Command errored out with exit status 1:
     command: /home/vignesh/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vignesh/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/vignesh/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/vignesh/wav2letter/bindings/python/
    Complete output (36 lines):
    running develop
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    reading manifest file 'wav2letter.egg-info/SOURCES.txt'
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    make: *** No targets specified and no makefile found.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vignesh/wav2letter/bindings/python/setup.py", line 109, in <module>
        zip_safe=False,
      File "/home/vignesh/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/vignesh/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/vignesh/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/vignesh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/vignesh/miniconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/vignesh/miniconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/vignesh/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/vignesh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/vignesh/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/home/vignesh/wav2letter/bindings/python/setup.py", line 91, in build_extensions
        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
      File "/home/vignesh/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/vignesh/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vignesh/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/home/vignesh/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

i am getting a error like this any solution

**Comment by martin-frbg** [comment]
From what you wrote I cannot even guess what this has to do with OpenBLAS ?

**Comment by brada4** [comment]
@vigneshmj1997 you need to report bugs to issue tracker of wav2letter module. This is certainly wrong place, their docker does not include any signs of OpenBLAS.
