### ISSUE TITLE
`SYMBOLSUFFIX` doesn't seems to work in CMAKE build system

### ISSUE THREAD

**Issue by zhqrbitee** [xianyi/OpenBLAS#3998]
I'm trying to build openblas 0.3.23 (64-bit integer) and use it as blas/lapack for numpy in my WSL. 
Since numpy's docs suggests building openblas with `64_` symbol suffix (https://numpy.org/devdocs/user/building.html#bit-blas-and-lapack), so I tried below make cmd:
```bash
FC=gfortran USE_THREAD=1 USE_TLS=1 NUM_THREADS=64 DYNAMIC_ARCH=0 \
NO_STATIC=1 INTERFACE64=1 BINARY64=1 \
SYMBOLSUFFIX=64_ make shared
```
It works well and I can see symbols with `64_` suffix in the shared library:
```
00000000009593d0 T zunmrz_64_
0000000000959dc0 T zunmtr_64_
000000000095a540 T zupgtr_64_
000000000095a980 T zupmtr_64_
```

However, when I tried to switch to cmake system:
```bash
 cmake -B build64 -S OpenBLAS-0.3.23 \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_WITHOUT_LAPACK=OFF \
    -DBUILD_WITHOUT_CBLAS=OFF \
    -DBUILD_TESTING=OFF \
    -DNO_AFFINITY=ON \
    -DUSE_THREAD=1 \
    -DUSE_TLS=1 \
    -DNO_WARMUP=1 \
    -DNUM_THREADS=64 \
    -DDYNAMIC_ARCH=OFF \
    -DINTERFACE64=1 \
    -DBINARY64=1 \
    -DSYMBOLSUFFIX=64_
````
It builds fine, but the shared library generated doesn't has `64_` symbol suffix:
```
0000000000953c70 T zunmrz_
00000000009545f0 T zunmtr_
0000000000954d30 T zupgtr_
0000000000955150 T zupmtr_
```
I noticed that the `exports/gensymbol` cmd, which seems used to rename symbols, gives some error messages, though it doesn't stop the cmake building process:
```bash
xxx/exports/gensymbol objcopy x86_64 _ 0 0 0 0 0 0 "" "64_" 0 false ON ON ON ON > xxx/build64/objcopy.def
```  
I believe the `exports/gensymbol ` is a bash script that expects `0/1` as boolean inputs and the cmake `false/ON` is unknown to it, so we need to convert itto `0/1` first:
```
--- CMakeLists.txt.1    2023-04-09 00:57:02.275990909 -0700
+++ CMakeLists.txt      2023-04-08 19:27:39.000000000 -0700
@@ -400,7 +400,7 @@

   if (NOT USE_PERL)
   add_custom_command(TARGET ${OpenBLAS_LIBNAME}_shared POST_BUILD
-    COMMAND  ${PROJECT_SOURCE_DIR}/exports/gensymbol "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BUILD_LAPACK_DEPRECATED}" "${BUILD_BFLOAT16}" "${BUILD_SINGLE}" "${BUILD_DOUBLE}" "${BUILD_COMPLEX}" "${BUILD_COMPLEX16}" > ${PROJECT_BINARY_DIR}/objcopy.def
+    COMMAND  ${PROJECT_SOURCE_DIR}/exports/gensymbol "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "$<BOOL:${BUILD_LAPACK_DEPRECATED}>" "$<BOOL:${BUILD_BFLOAT16}>" "$<BOOL:${BUILD_SINGLE}>" "$<BOOL:${BUILD_DOUBLE}>" "$<BOOL:${BUILD_COMPLEX}>" "$<BOOL:${BUILD_COMPLEX16}>" > ${PROJECT_BINARY_DIR}/objcopy.def
     COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def  ${PROJECT_BINARY_DIR}/lib/lib${OpenBLAS_LIBNAME}.so
     COMMENT "renaming symbols"
     )
```
However, even after this patch, I'm still unable to see `64_` symbol suffix though the `exports/gensymbol` command doesn't complain anything. 

I'm using `cmake 3.26.3` with `gcc/gfortan: 12.2.1 20230211` (arch linux) and below are outputs from the cmake:
```
-- Using 64-bit integers.
-- GEMM multithread threshold set to 4.
-- Multi-threading enabled with 64 threads.
-- Running getarch
-- GETARCH results:
CORE=ZEN
LIBCORE=zen
NUM_CORES=16
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
HAVE_SSSE3=1
HAVE_SSE4_1=1
HAVE_SSE4_2=1
HAVE_SSE4A=1
HAVE_AVX=1
HAVE_AVX2=1
HAVE_FMA3=1
MAKE += -j 16
...
-- fortran lapack
-- Building Single Precision
-- Building Double Precision
-- Building Single Precision Complex
-- Building Double Precision Complex
-- adding suffix 64_ to names of exported symbols in openblas_64
-- Generating openblas_config.h in include/openblas64
-- Generating f77blas.h in include/openblas64
-- Generating cblas.h in include/openblas64
-- Copying LAPACKE header files to include/openblas64
```

Let me know if you need more info to reproduce this issue.

**Comment by martin-frbg** [comment]
~~cmake build is a bit different "historically" in that it adds the 64 suffix automatically with INTERFACE64, maybe this collides with an express SYMBOLSUFFIX option currently~~

**Comment by zhqrbitee** [comment]
> cmake build is a bit different "historically" in that it adds the 64 suffix automatically with INTERFACE64, maybe this collides with an express SYMBOLSUFFIX option currently.

I try to remove `-DSYMBOLSUFFIX=64_` and do a clean rebuild, I did see the shared library has a `_64` name suffix, i.e. the `libsuffix` below. 
```
libdir=/home/zhqrbitee/build/test/lib
libsuffix=_64
includedir=/home/zhqrbitee/build/test/include/openblas64

openblas_config=USE_64BITINT=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE= DYNAMIC_ARCH=OFF DYNAMIC_OLDER=OFF NO_AFFINITY=ON USE_OPENMP= ZEN MAX_THREADS=64 
Name: OpenBLAS
Description: OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
Version: 
URL: https://github.com/xianyi/OpenBLAS
Libs:  -L${libdir} -lopenblas${libsuffix} 
Cflags: -I${includedir}
```
But I still didn't see the `64_` symbol suffix in the shared library using `nm -D build64/lib/libopenblas_64.so`. Is there anything I miss?

**Comment by martin-frbg** [comment]
Unfortunately you are right, it looks like option passing to `gensymbol` got broken in cmake builds. Will try to find time to fix it this week...

**Comment by martin-frbg** [comment]
#3999 should fix (most of) this - you were right about the untranslated "ON/OFF" ending up on the options list of gensymbol, but the CMAKE `BOOL:` expression you tried apparently does not work outside of conditionals. 
Currently looking into an inconsistency in the handling of BUILD_LAPACK_DEPRECATED between gmake and CMAKE builds (and within the CMAKE build process as well, again potentially leading to non-suffixed symbols appearing in the library) ...

**Comment by rgommers** [comment]
I was puzzled by the following for a bit. The CMake build contains the right symbols, but also the non-suffixed ones. And the latter ones are the ones that show up in the dynamic symbol table:
```
$ mkdir build && cd build
$ cmake .. -DINTERFACE64=1 -DSYMBOLSUFFIX=64_ -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON
$ cmake --build . -j

$ nm -gD lib/libopenblas_64.so | rg cblas_dgemm
00000000000d4dd0 T cblas_dgemm
00000000000d6a64 T cblas_dgemmt

$ readelf -s lib/libopenblas_64.so | rg cblas_dgemm
  4950: 00000000000d4dd0  1838 FUNC    GLOBAL DEFAULT   12 cblas_dgemm
  5369: 00000000000d6a64  3552 FUNC    GLOBAL DEFAULT   12 cblas_dgemmt
   839: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS cblas_dgemm.c
   856: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS cblas_dgemmt.c
  9462: 00000000000d6a64  3552 FUNC    GLOBAL DEFAULT   12 cblas_dgemmt64_
 15794: 00000000000d4dd0  1838 FUNC    GLOBAL DEFAULT   12 cblas_dgemm64_
```

The gmake build on the contrary looks as expected:
```
$ make INTERFACE64=1 SYMBOLSUFFIX=64
$ make install PREFIX=$PWD/tmp INTERFACE64=1 SYMBOLSUFFIX=64_

$ nm -gD tmp/lib/libopenblas64_.so | rg cblas_dgemm
00000000000b6350 T cblas_dgemm64_
00000000000b83e0 T cblas_dgemmt64_

$ readelf -s tmp/lib/libopenblas64_.so | rg cblas_dgemm
   540: 00000000000b83e0  2915 FUNC    GLOBAL DEFAULT   12 cblas_dgemmt64_
  2770: 00000000000b6350  1383 FUNC    GLOBAL DEFAULT   12 cblas_dgemm64_
 12639: 00000000000b83e0  2915 FUNC    GLOBAL DEFAULT   12 cblas_dgemmt64_
 15588: 00000000000b6350  1383 FUNC    GLOBAL DEFAULT   12 cblas_dgemm64_
```

This may trip up other people, so I thought I'd comment. I haven't yet figured out why the `objcopy` invocation that `make` does works while the one from `cmake` does not (to the same extent).

There's another reason the `objcopy` may fail: when LTO is enabled.

**Comment by martin-frbg** [comment]
@rgommers I cannot reproduce your `nm` output locally, for me it only reports the suffixed versions as expected. The readelf output, however, looks similar to yours  - but I notice the second column, presumably the entry point/offset, shows the same value for suffixed and non-suffixed symbol. Maybe that is only some artifact of the ELF format (or readelf's presentation of it) that `nm` manages to suppress ?

**Comment by rgommers** [comment]
Yeah it's odd, I don't think I've seen this before. The second column of the `readelf` output indeed shows that the `64_` ones and the non-suffixed ones are aliases. I read in a few places that `objcopy --redefine-syms` has trouble updating the dynamic symbol table, but it's all pretty obscure. What puzzles me most is why gmake/cmake don't align, because they're invoking the same `objcopy` executable with what looks like the same `.def` file.

**Comment by yuyichao** [comment]
AFAICT, the make version of the build system applies objcopy on the static library before it's linked into a shared library.

objcopy can edit everything in the static library just fine since it's not linked yet and the sections can be resized as much as it wants (and resize may be necessary when doing symbol remapping) but it can't do so for the the linked shared library.


Edit: note that

https://github.com/OpenMathLib/OpenBLAS/blob/66c2c41e996bffbb65c49c31482fc7b3fa40b415/exports/Makefile#L219-L221

The one being copied is `$(LIBNAME)`, not `$(LIBSONAME)`

**Comment by yuyichao** [comment]
Ref https://binutils.sourceware.narkive.com/OX0ugydt/objcopy-redefine-sym-on-dynsym-section

**Comment by martin-frbg** [comment]
Ah, good catch, one of those elusive "the cmake build may not produce the same makefiles" cases then. :( 
I wonder if this requires fixing though, as I believe recent consensus among implementers was to move to a single library that provides both LP64 and ILP64 symbols in the medium term anyway.

**Comment by dmikushin** [comment]
Yes, the following `SYMBOLPREFIX` tweak currently being used in CMake is not going to work in Linux:

```cmake
  add_custom_command(TARGET ${fstfrMM_LIBNAME}_shared POST_BUILD
	COMMAND  ${PROJECT_SOURCE_DIR}/exports/gensymbol "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BLD}" "${BBF16}" "${BS}" "${BD}" "${BC}" "${BZ}" > ${PROJECT_BINARY_DIR}/objcopy.def
    COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def $<TARGET_FILE:${fstfrMM_LIBNAME}_shared>
    COMMENT "renaming symbols"
    )
```

Although you may see that the symbols are properly renamed in the shared library, the linker will not find them, because [objcopy renaming does not work with dynamic symbols](https://stackoverflow.com/questions/3921440/still-reports-undefined-symbol-new-add-after-use-objcopy-redefine-sym-add).

But the same method will work, if applied to the _static_ library, not to the shared.

**Comment by martin-frbg** [comment]
Meh. So we need to force building the static library when the user wants symbol pre- or postfixing, apply the objcopy magic there and build the shared library from that just like in the gmake build. And then throw away the static library when the user did not want it ? (I get the feeling that it may have been done that way until someone came along with a big patch and a categorical "one simply does not build both kinds of libraries on CMAKE".)

**Comment by dmikushin** [comment]
There are still some aspects to investigate before implementing the final pipeline. I've just discovered that dynamic OpenBLAS is still in clash with a prefixed static OpenBLAS, if they both are linked to the same executable.

The symptom is when the prefixed function is called by the app, a subsequent call to `cblas_dznrm2` is dynamically resolved to  0x0 and segfaults. Note `cblas_dznrm2` is deleted from my prefixed OpenBLAS. Looks like it is still being attempted instead of calling the right one from the official OpenBLAS. Yes, I use `DYNAMIC_ARCH`. I've prefixed some more goto* symbols, but the problem persists, I'm puzzled.

```
Thread 1 "test_mymm" hit Breakpoint 1, 0x00007ffff510b670 in cblas_dznrm2 () from /lib/x86_64-linux-gnu/libopenblas.so.0
(gdb) bt
#0  0x00007ffff510b670 in cblas_dznrm2 () from /lib/x86_64-linux-gnu/libopenblas.so.0
#1  0x00005555555558fa in main (argc=1, argv=0x7fffffffdfd8) at /home/marcusmae/org/my/ThirdParty/myblas/src/test/test_mymm.cpp:53
(gdb) disass
Dump of assembler code for function cblas_dznrm2:
=> 0x00007ffff510b670 <+0>:	endbr64 
   0x00007ffff510b674 <+4>:	test   %edi,%edi
   0x00007ffff510b676 <+6>:	jle    0x7ffff510b690 <cblas_dznrm2+32>
   0x00007ffff510b678 <+8>:	mov    0x22c9601(%rip),%rax        # 0x7ffff73d4c80
   0x00007ffff510b67f <+15>:	movslq %edx,%rdx
   0x00007ffff510b682 <+18>:	movslq %edi,%rdi
   0x00007ffff510b685 <+21>:	mov    (%rax),%rax
   0x00007ffff510b688 <+24>:	jmp    *0xb48(%rax)
   0x00007ffff510b68e <+30>:	xchg   %ax,%ax
   0x00007ffff510b690 <+32>:	pxor   %xmm0,%xmm0
   0x00007ffff510b694 <+36>:	ret    
End of assembler dump.
(gdb) b *0x00007ffff510b688
Breakpoint 2 at 0x7ffff510b688
(gdb) c
Continuing.

Thread 1 "test_mymm" hit Breakpoint 2, 0x00007ffff510b688 in cblas_dznrm2 () from /lib/x86_64-linux-gnu/libopenblas.so.0
(gdb) p *($rax + 0xb48)
$1 = 0
```

**Comment by dmikushin** [comment]
@martin-frbg , I gave up my attempt to use the prefixed static library, it feels that it won't work anyway. But your idea above works very well for the shared library. FWIW, I'm attaching out of thee patch that might be useful:

```patch
From cb20722307964c475d2e591c5a3a38b76ec3ae86 Mon Sep 17 00:00:00 2001
From: Dmitry Mikushin <dmitry@kernelgen.org>
Date: Thu, 8 Feb 2024 19:10:50 +0100
Subject: [PATCH] Changing the procedure of symbols decoration with SYMBOLPREFIX:

Since the objcopy cannot redefine dynamic symbols as pointed out in #3998,
the redefine command has to run eariler. This patch implements idea that
plays best with the CMake mechanics: first the static library is generated,
and then its symbols are redefined. In case the shared library is requested,
it is created from the static library with already redefined symbols. The
static library is linked to shared in WHOLE_ARCHIVE mode to embed all symbols.
The use of portable WHOLE_ARCHIVE idiom requires CMake 3.24 and can be
replaced with platform-specific non-portable flags if older versions of
CMake are desired.

Co-authored-by: Martin Kroeker <martin@ru*********************g.de>
---
 CMakeLists.txt | 242 +++++++++++++++++++++++++------------------------
 dummy.c        |   0
 2 files changed, 126 insertions(+), 116 deletions(-)
 create mode 100644 dummy.c

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 12bc2f18a..4854fce05 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,7 +2,8 @@
 ## Author: Hank Anderson <hank@statease.com>
 ##
 
-cmake_minimum_required(VERSION 3.5)
+# Note: "$<LINK_LIBRARY:WHOLE_ARCHIVE,tgt>" is a 3.24 feature
+cmake_minimum_required(VERSION 3.24 FATAL_ERROR)
 
 project(openblas C CXX ASM)
 
@@ -143,11 +144,117 @@ if(MSVC)
   set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${PROJECT_BINARY_DIR}/lib/Release)
 endif ()
 
-# get obj vars into format that add_library likes: $<TARGET_OBJS:objlib> (see http://www.cmake.org/cmake/help/v3.0/command/add_library.html)
+if (NOT ${SYMBOLPREFIX}${SYMBOLSUFFIX} STREQUAL "")
+  if (NOT DEFINED ARCH)
+    set(ARCH_IN "x86_64")
+  else()
+    set(ARCH_IN ${ARCH})
+  endif()
+
+  if (${CORE} STREQUAL "generic")
+    set(ARCH_IN "GENERIC")
+  endif ()
+
+  if (NOT DEFINED EXPRECISION)
+    set(EXPRECISION_IN 0)
+  else()
+    set(EXPRECISION_IN ${EXPRECISION})
+  endif()
+
+  if (NOT DEFINED NO_CBLAS)
+    set(NO_CBLAS_IN 0)
+  else()
+    set(NO_CBLAS_IN ${NO_CBLAS})
+  endif()
+
+  if (NOT DEFINED NO_LAPACK)
+    set(NO_LAPACK_IN 0)
+  else()
+    set(NO_LAPACK_IN ${NO_LAPACK})
+  endif()
+
+  if (NOT DEFINED NO_LAPACKE)
+    set(NO_LAPACKE_IN 0)
+  else()
+    set(NO_LAPACKE_IN ${NO_LAPACKE})
+  endif()
+
+  if (NOT DEFINED NEED2UNDERSCORES)
+    set(NEED2UNDERSCORES_IN 0)
+  else()
+    set(NEED2UNDERSCORES_IN ${NEED2UNDERSCORES})
+  endif()
+
+  if (NOT DEFINED ONLY_CBLAS)
+    set(ONLY_CBLAS_IN 0)
+  else()
+    set(ONLY_CBLAS_IN ${ONLY_CBLAS})
+  endif()
+
+  if (NOT DEFINED BU)
+    set(BU _)
+  endif()
+
+  if (NOT ${SYMBOLPREFIX} STREQUAL "")
+    message(STATUS "adding prefix ${SYMBOLPREFIX} to names of exported symbols in ${openblas_LIBNAME}")
+  endif()
+  if (NOT ${SYMBOLSUFFIX} STREQUAL "")
+    message(STATUS "adding suffix ${SYMBOLSUFFIX} to names of exported symbols in ${openblas_LIBNAME}")
+  endif()
+
+  if (${BUILD_LAPACK_DEPRECATED})
+	  set (BLD 1)
+  else ()
+	  set (BLD 0)
+  endif()
+  if (${BUILD_BFLOAT16})
+	  set (BBF16 1)
+  else ()
+	  set (BBF16 0)
+  endif()
+  if (${BUILD_SINGLE})
+	  set (BS 1)
+  else ()
+	  set (BS 0)
+  endif()
+  if (${BUILD_DOUBLE})
+	  set (BD 1)
+  else ()
+	  set (BD 0)
+  endif()
+  if (${BUILD_COMPLEX})
+	  set (BC 1)
+  else ()
+	  set (BC 0)
+  endif()
+  if (${BUILD_COMPLEX16})
+	  set (BZ 1)
+  else ()
+	  set (BZ 0)
+  endif()
+  if (NOT USE_PERL)
+  add_custom_command(OUTPUT ${PROJECT_BINARY_DIR}/objcopy.def
+	COMMAND ${PROJECT_SOURCE_DIR}/exports/gensymbol "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BLD}" "${BBF16}" "${BS}" "${BD}" "${BC}" "${BZ}" > ${PROJECT_BINARY_DIR}/objcopy.def
+    COMMENT "Building renaming symbols table"
+    DEPENDS ${PROJECT_SOURCE_DIR}/exports/gensymbol
+    )
+  else()
+  add_custom_command(OUTPUT ${PROJECT_BINARY_DIR}/objcopy.def
+    COMMAND perl ${PROJECT_SOURCE_DIR}/exports/gensymbol.pl "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BLD}" "${BBF16}" "${BS}" "${BD}" "${BC}" "${BZ}" > ${PROJECT_BINARY_DIR}/objcopy.def
+    COMMENT "Building renaming symbols table"
+    DEPENDS ${PROJECT_SOURCE_DIR}/exports/gensymbol.pl
+    )
+  endif()
+endif()
+
 set(TARGET_OBJS "")
 foreach (SUBDIR ${SUBDIRS})
   add_subdirectory(${SUBDIR})
+  
+  # Get obj vars into format that add_library likes: $<TARGET_OBJS:objlib>
+  # (see http://www.cmake.org/cmake/help/v3.0/command/add_library.html)  
   string(REPLACE "/" "_" subdir_obj ${SUBDIR})
+
   list(APPEND TARGET_OBJS "$<TARGET_OBJECTS:${subdir_obj}>")
 endforeach ()
 
@@ -173,17 +280,28 @@ set(openblas_LIBS "")
 if(BUILD_STATIC_LIBS)
   add_library(${openblas_LIBNAME}_static STATIC ${TARGET_OBJS} ${openblas_DEF_FILE})
   target_include_directories(${openblas_LIBNAME}_static INTERFACE $<INSTALL_INTERFACE:include/openblas${SUFFIX64}>)
+
+  # Decorate symbols with prefix for the static library.
+  if (NOT ${SYMBOLPREFIX}${SYMBOLSUFFIX} STREQUAL "")
+    add_custom_command(TARGET ${openblas_LIBNAME}_static POST_BUILD
+      COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def $<TARGET_FILE:${openblas_LIBNAME}_static>
+      COMMENT "Running objcopy on ${openblas_LIBNAME}_static"
+      DEPENDS ${PROJECT_BINARY_DIR}/objcopy.def)
+  endif()
+
   list(APPEND openblas_LIBS ${openblas_LIBNAME}_static)
 endif()
 if(BUILD_SHARED_LIBS)
-  add_library(${openblas_LIBNAME}_shared SHARED ${TARGET_OBJS} ${openblas_DEF_FILE})
+  add_library(${openblas_LIBNAME}_shared SHARED "dummy.c" ${openblas_DEF_FILE})
   target_include_directories(${openblas_LIBNAME}_shared INTERFACE $<INSTALL_INTERFACE:include/openblas${SUFFIX64}>)
+  target_link_libraries(${openblas_LIBNAME}_shared PRIVATE $<LINK_LIBRARY:WHOLE_ARCHIVE,${openblas_LIBNAME}_static>)
   list(APPEND openblas_LIBS ${openblas_LIBNAME}_shared)
 endif()
 if(BUILD_STATIC_LIBS)
-  add_library(${openblas_LIBNAME}::${openblas_LIBNAME} ALIAS ${openblas_LIBNAME}_static)
-else()
-  add_library(${openblas_LIBNAME}::${openblas_LIBNAME} ALIAS ${openblas_LIBNAME}_shared)
+  add_library(${openblas_LIBNAME}::static ALIAS ${openblas_LIBNAME}_static)
+endif()
+if(BUILD_SHARED_LIBS)
+  add_library(${openblas_LIBNAME}::shared ALIAS ${openblas_LIBNAME}_shared)
 endif()
 
 set_target_properties(${openblas_LIBS} PROPERTIES OUTPUT_NAME ${openblas_LIBNAME})
@@ -194,7 +312,7 @@ if (${CMAKE_SYSTEM_NAME} MATCHES "AIX|Android|Linux|FreeBSD|OpenBSD|NetBSD|Drago
     target_link_libraries(${openblas_LIBNAME}_static m)
   endif()
   if(BUILD_SHARED_LIBS)
-    target_link_libraries(${openblas_LIBNAME}_shared m)
+    target_link_libraries(${openblas_LIBNAME}_shared PUBLIC m)
   endif()
 endif()
 
@@ -254,111 +372,6 @@ set_target_properties(${openblas_LIBS} PROPERTIES
   SOVERSION ${openblas_MAJOR_VERSION}
 )
 
-if (BUILD_STATIC_LIBS AND NOT ${SYMBOLPREFIX}${SYMBOLSUFFIX} STREQUAL "")
-  if (NOT DEFINED ARCH)
-    set(ARCH_IN "x86_64")
-  else()
-    set(ARCH_IN ${ARCH})
-  endif()
-
-  if (${CORE} STREQUAL "generic")
-    set(ARCH_IN "GENERIC")
-  endif ()
-
-  if (NOT DEFINED EXPRECISION)
-    set(EXPRECISION_IN 0)
-  else()
-    set(EXPRECISION_IN ${EXPRECISION})
-  endif()
-
-  if (NOT DEFINED NO_CBLAS)
-    set(NO_CBLAS_IN 0)
-  else()
-    set(NO_CBLAS_IN ${NO_CBLAS})
-  endif()
-
-  if (NOT DEFINED NO_LAPACK)
-    set(NO_LAPACK_IN 0)
-  else()
-    set(NO_LAPACK_IN ${NO_LAPACK})
-  endif()
-
-  if (NOT DEFINED NO_LAPACKE)
-    set(NO_LAPACKE_IN 0)
-  else()
-    set(NO_LAPACKE_IN ${NO_LAPACKE})
-  endif()
-
-  if (NOT DEFINED NEED2UNDERSCORES)
-    set(NEED2UNDERSCORES_IN 0)
-  else()
-    set(NEED2UNDERSCORES_IN ${NEED2UNDERSCORES})
-  endif()
-
-  if (NOT DEFINED ONLY_CBLAS)
-    set(ONLY_CBLAS_IN 0)
-  else()
-    set(ONLY_CBLAS_IN ${ONLY_CBLAS})
-  endif()
-
-  if (NOT DEFINED BU)
-    set(BU _)
-  endif()
-
-  if (NOT ${SYMBOLPREFIX} STREQUAL "")
-    message(STATUS "adding prefix ${SYMBOLPREFIX} to names of exported symbols in ${openblas_LIBNAME}")
-  endif()
-  if (NOT ${SYMBOLSUFFIX} STREQUAL "")
-    message(STATUS "adding suffix ${SYMBOLSUFFIX} to names of exported symbols in ${openblas_LIBNAME}")
-  endif()
-
-  if (${BUILD_LAPACK_DEPRECATED})
-	  set (BLD 1)
-  else ()
-	  set (BLD 0)
-  endif()
-  if (${BUILD_BFLOAT16})
-	  set (BBF16 1)
-  else ()
-	  set (BBF16 0)
-  endif()
-  if (${BUILD_SINGLE})
-	  set (BS 1)
-  else ()
-	  set (BS 0)
-  endif()
-  if (${BUILD_DOUBLE})
-	  set (BD 1)
-  else ()
-	  set (BD 0)
-  endif()
-  if (${BUILD_COMPLEX})
-	  set (BC 1)
-  else ()
-	  set (BC 0)
-  endif()
-  if (${BUILD_COMPLEX16})
-	  set (BZ 1)
-  else ()
-	  set (BZ 0)
-  endif()
-  if (NOT USE_PERL)
-  add_custom_command(TARGET ${openblas_LIBNAME}_static POST_BUILD
-	COMMAND ${PROJECT_SOURCE_DIR}/exports/gensymbol "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BLD}" "${BBF16}" "${BS}" "${BD}" "${BC}" "${BZ}" > ${PROJECT_BINARY_DIR}/objcopy.def
-    COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def $<TARGET_FILE:${openblas_LIBNAME}_static>
-    COMMENT "renaming symbols"
-    DEPENDS ${PROJECT_SOURCE_DIR}/exports/gensymbol
-    )
-  else()
-  add_custom_command(TARGET ${openblas_LIBNAME}_static POST_BUILD
-    COMMAND perl ${PROJECT_SOURCE_DIR}/exports/gensymbol.pl "objcopy" "${ARCH}" "${BU}" "${EXPRECISION_IN}" "${NO_CBLAS_IN}" "${NO_LAPACK_IN}" "${NO_LAPACKE_IN}" "${NEED2UNDERSCORES_IN}" "${ONLY_CBLAS_IN}" \"${SYMBOLPREFIX}\" \"${SYMBOLSUFFIX}\" "${BLD}" "${BBF16}" "${BS}" "${BD}" "${BC}" "${BZ}" > ${PROJECT_BINARY_DIR}/objcopy.def
-    COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def $<TARGET_FILE:${openblas_LIBNAME}_static>
-    COMMENT "renaming symbols"
-    DEPENDS ${PROJECT_SOURCE_DIR}/exports/gensymbol.pl
-    )
-  endif()
-endif()
-
 
 
 # Benchmarking BLAS Level 3
@@ -377,14 +390,11 @@ endif()
 
 # Install libraries
 if(BUILD_SHARED_LIBS AND BUILD_STATIC_LIBS)
-  install(TARGETS ${openblas_LIBNAME}_shared
+  install(TARGETS ${openblas_LIBNAME}_shared ${openblas_LIBNAME}_static
     EXPORT "openblas${SUFFIX64}Targets"
     RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
     ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
     LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} )
-  install(TARGETS ${openblas_LIBNAME}_static
-    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
-    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} )
 else()
   install(TARGETS ${openblas_LIBS}
     EXPORT "openblas${SUFFIX64}Targets"
diff --git a/dummy.c b/dummy.c
new file mode 100644
index 000000000..e69de29bb
-- 
2.34.1

```

**Comment by dmikushin** [comment]
JFYI, with `SYMBOLPREFIX` applied, shared OpenBLAS **still clashes** with another OpenBLAS via utility functions, such as `zgemm_oncopy_HASWELL`. This function belongs to tiling/threading/dispatching infrastructure, and all of them are completely undecorated.

I had to decorate all of them:

```cmake
    add_custom_command(TARGET ${openblas_LIBNAME}_static POST_BUILD
      COMMAND nm -j --defined-only $<TARGET_FILE:${openblas_LIBNAME}_static> | sort | uniq | awk '{print $$0 \" openblas_\"$$0}' > ${PROJECT_BINARY_DIR}/objcopy.def
      COMMAND objcopy -v --redefine-syms ${PROJECT_BINARY_DIR}/objcopy.def $<TARGET_FILE:${openblas_LIBNAME}_static>
      COMMENT "Running objcopy on ${openblas_LIBNAME}_static")
```

This method has finally put the mess to an end. Note I'm using UNIX utils good for Linux/BSD only.

**Comment by martin-frbg** [comment]
I had started to decorate them too but then the question came up if going for visibility "hidden" would be a better choice. Need to resume that work
